language: emacs-lisp
sudo: false
cache:
  - directories:
      - "$HOME/emacs/"
env:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
install:
  - cask install
script:
  - cask exec ert-runner
notifications:
email: false
